### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bhipple** [markandrus/slack-lambdabot#2]
I'd like to use this on my team's slack as a way to introduce peers to Haskell, but it doesn't have a LICENSE file.  Would you be willing to specify one so that I can get it approved?

**Comment by markandrus** [comment]
Hi @bhipple, thanks for opening an issue. I've just pushed a LICENSE.md in eb8fa9c.

**Comment by markandrus** [comment]
> I'd like to use this on my team's slack as a way to introduce peers to Haskell

Regarding this, good luck! This project is currently unmaintained and I remember having some trouble with it that ultimately led me to take a break from it. Something about making additional libraries available.

**Comment by bhipple** [comment]
Thanks for the heads up.  This is a low priority side-project for me, so it might sit for a few weeks, but if I get it working I'll let you know!
